version: "3.10"
services:
  ftp:
    image: fauria/vsftpd:latest
    restart: always
    volumes:
      - ./vsftpd.conf:/etc/vsftpd.conf
      - ./data:/home/vsftpd
    environment:
      - FTP_USER={ftp_username}
      - FTP_PASS={ftp_password}
      - PASV_ADDRESS={ftp_domain}
    tty: true
    stdin_open: true
