version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: systemoad_db
      MYSQL_USER: user
      MYSQL_PASSWORD: ser1234gio
      MYSQL_ROOT_PASSWORD: ser1234gio
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ser1234gio
    ports:
      - "8080:80"

volumes:
  db_data:
